cergy_book:
    resource: "@CergyBookBundle/Controller/"
    type:     annotation
    prefix:   /book

cergy_api:
    resource: "@CergyApiBundle/Controller/NewsController.php"
    type:     rest
    prefix:   /api

cergy_user:
    resource: "@CergyUserBundle/Controller/"
    type:     annotation
    prefix:   /

cergy_news:
    resource: "@CergyNewsBundle/Controller/"
    type:     annotation
    prefix:   /news

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
