Cergy\NewsBundle\Entity\News:
    properties:
        title:
            - NotBlank: ~
            - Length:
                min: 3
                max: 100
                minMessage: Trop petit
                maxMessage: Trop long {{ limit }}

        content:
            - NotBlank: ~
            - Length:
                min: 4
                minMessage: Le message doit être supérieur à 4 caractères
            - NotEqualTo:
                value: test
                message: Ne peut pas être égal à {{ value }}
